version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: opennotes_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # No external ports exposed - internal network only
    networks:
      - opennotes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    # No external ports exposed - internal network only
    networks:
      - opennotes-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  nats:
    image: nats:2.10-alpine
    command:
      - "--jetstream"
      - "--store_dir=/data"
      - "--http_port=8222"  # Enable HTTP monitoring for healthcheck
    volumes:
      - nats_data:/data
    # No external ports exposed - internal network only
    networks:
      - opennotes-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/opennotes_bot
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - PORT=3000
    env_file:
      - .env
    ports:
      - "3000:3000"  # Only expose bot API for dashboard access
    volumes:
      - ./logs:/app/logs
    networks:
      - opennotes-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  opennotes-network:
    driver: bridge
    name: opennotes-network

volumes:
  postgres_data:
  redis_data:
  nats_data: